version: '3.0'

services:
    server:
        build: .
        environment:
            - DATABASE_HOST=db
        depends_on:
            - db
        restart: always
        ports:
            - 8080:8080
        volumes:
            - .:/app
    db:
        build: ./mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: farmosa_db